services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: batch-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 30s
      retries: 3

  batch-service:
    image: limcpf/telegram-rabbitmq-batch-manager:v0.0.2
    # build:
    #   context: .
    #   dockerfile: src/main/docker/Dockerfile.multistage
    container_name: batch-service
    ports:
      - "8080:8080"
    environment:
      AMQP_HOST: rabbitmq
      AMQP_PORT: 5672
      AMQP_USERNAME: guest
      AMQP_PASSWORD: guest
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    volumes:
      - ./batch-data:/work/data
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: always

volumes:
  rabbitmq_data:
